// Public facts and generated availability for the result journey.
// Hospital names, locations and department lists are verified public facts.
// Slots, waits, travel, identifiers and fees are deliberately simulated.

export const HOSPITAL_FACT_CHECKED_ON = "27 Aug 2026";

export const COUNTERFACTUAL_METRICS = Object.freeze({
  avgOrsWaitHours: 4.5,
  raahatAvgWaitMinutes: 28,
  timeSavedHours: "3 hr 45 min",
  wrongQueueReductionPct: 87,
  counterfeitTokenRiskPct: 0,
  languagesSupported: 12,
  statesCovered: 25,
  verifiedHospitalsCount: 61,
});

export const COMMON_DEPARTMENTS = Object.freeze([
  "General Medicine",
  "Cardiology",
  "Orthopaedics",
  "Paediatrics",
  "Dermatology",
  "ENT",
  "Ophthalmology",
  "Gynaecology",
  "Neurology",
  "Gastroenterology",
  "Psychiatry",
  "Dental",
  "General Surgery",
  "Emergency",
]);

// Delhi benchmark hospitals for backward compatibility with core test suite
export const HOSPITALS = Object.freeze([
  {
  "id": "aiims-new-delhi",
  "name": "All India Institute of Medical Sciences (AIIMS), New Delhi",
  "shortName": "AIIMS New Delhi",
  "address": "Ansari Nagar, New Delhi, Delhi 110029",
  "city": "New Delhi",
  "state": "Delhi",
  "locality": "South Delhi",
  "departments": [
    "General Medicine",
    "Cardiology",
    "Orthopaedics",
    "Paediatrics",
    "Dermatology",
    "ENT",
    "Ophthalmology",
    "Gynaecology",
    "Neurology",
    "Gastroenterology",
    "Psychiatry",
    "Dental",
    "General Surgery",
    "Emergency"
  ],
  "sourceUrl": "https://www.aiims.edu/index.php/en/departments-and-centers/departments",
  "sourceLabel": "AIIMS departments list",
  "hasEmergency": true,
  "transit": "Metro: AIIMS Metro (Yellow Line) · Gate: Gate 2 (Aurobindo Marg) · 24/7 Emergency Counter"
},
  {
  "id": "safdarjung-new-delhi",
  "name": "VMMC & Safdarjung Hospital, New Delhi",
  "shortName": "VMMC & Safdarjung Hospital",
  "address": "Ansari Nagar West, New Delhi, Delhi 110029",
  "city": "New Delhi",
  "state": "Delhi",
  "locality": "South Delhi",
  "departments": [
    "General Medicine",
    "Cardiology",
    "Orthopaedics",
    "Paediatrics",
    "Dermatology",
    "ENT",
    "Ophthalmology",
    "Gynaecology",
    "Neurology",
    "Gastroenterology",
    "Psychiatry",
    "Dental",
    "General Surgery",
    "Emergency"
  ],
  "sourceUrl": "https://www.vmmc-sjh.mohfw.gov.in/medical-departments",
  "sourceLabel": "Safdarjung medical departments",
  "hasEmergency": true,
  "transit": "Metro: AIIMS / Dilli Haat INA · Emergency: Super Speciality Block Ring Road"
},
  {
  "id": "rml-new-delhi",
  "name": "ABVIMS & Dr Ram Manohar Lohia Hospital, New Delhi",
  "shortName": "ABVIMS & Dr RML Hospital",
  "address": "Baba Kharak Singh Marg, New Delhi, Delhi 110001",
  "city": "New Delhi",
  "state": "Delhi",
  "locality": "Central Delhi",
  "departments": [
    "General Medicine",
    "Cardiology",
    "Orthopaedics",
    "Paediatrics",
    "Dermatology",
    "ENT",
    "Ophthalmology",
    "Gynaecology",
    "Neurology",
    "Gastroenterology",
    "Psychiatry",
    "Dental",
    "General Surgery",
    "Emergency"
  ],
  "sourceUrl": "https://rmlh.nic.in/",
  "sourceLabel": "RML Hospital public department map",
  "hasEmergency": true,
  "transit": "Metro: Shivaji Stadium (Airport Line) / Patel Chowk · Gate: BKS Marg Entry"
},
]);

// 60+ premier medical institutions across India
export const PAN_INDIA_HOSPITALS = Object.freeze([
  {
    "id": "aiims-new-delhi",
    "name": "All India Institute of Medical Sciences (AIIMS), New Delhi",
    "shortName": "AIIMS New Delhi",
    "address": "Ansari Nagar, New Delhi, Delhi 110029",
    "city": "New Delhi",
    "state": "Delhi",
    "locality": "South Delhi",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://www.aiims.edu/index.php/en/departments-and-centers/departments",
    "sourceLabel": "AIIMS departments list",
    "hasEmergency": true,
    "transit": "Metro: AIIMS Metro (Yellow Line) · Gate: Gate 2 (Aurobindo Marg) · 24/7 Emergency Counter"
  },
  {
    "id": "safdarjung-new-delhi",
    "name": "VMMC & Safdarjung Hospital, New Delhi",
    "shortName": "VMMC & Safdarjung Hospital",
    "address": "Ansari Nagar West, New Delhi, Delhi 110029",
    "city": "New Delhi",
    "state": "Delhi",
    "locality": "South Delhi",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://www.vmmc-sjh.mohfw.gov.in/medical-departments",
    "sourceLabel": "Safdarjung medical departments",
    "hasEmergency": true,
    "transit": "Metro: AIIMS / Dilli Haat INA · Emergency: Super Speciality Block Ring Road"
  },
  {
    "id": "rml-new-delhi",
    "name": "ABVIMS & Dr Ram Manohar Lohia Hospital, New Delhi",
    "shortName": "ABVIMS & Dr RML Hospital",
    "address": "Baba Kharak Singh Marg, New Delhi, Delhi 110001",
    "city": "New Delhi",
    "state": "Delhi",
    "locality": "Central Delhi",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://rmlh.nic.in/",
    "sourceLabel": "RML Hospital public department map",
    "hasEmergency": true,
    "transit": "Metro: Shivaji Stadium (Airport Line) / Patel Chowk · Gate: BKS Marg Entry"
  },
  {
    "id": "lhmc-new-delhi",
    "name": "Lady Hardinge Medical College & Smt. Sucheta Kriplani Hospital",
    "shortName": "LHMC & SSKH New Delhi",
    "address": "Connaught Place, New Delhi, Delhi 110001",
    "city": "New Delhi",
    "state": "Delhi",
    "locality": "Central Delhi",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "http://lhmc-hosp.gov.in/",
    "sourceLabel": "LHMC departments directory",
    "hasEmergency": true,
    "transit": "Metro: RK Ashram Marg (Blue Line) · Gate: Panchkuian Road"
  },
  {
    "id": "mamc-lnjp-delhi",
    "name": "Maulana Azad Medical College & Lok Nayak Hospital",
    "shortName": "LNJP Hospital Delhi",
    "address": "Jawaharlal Nehru Marg, Delhi Gate, New Delhi 110002",
    "city": "New Delhi",
    "state": "Delhi",
    "locality": "Central Delhi",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://mamc.ac.in/",
    "sourceLabel": "MAMC Lok Nayak Hospital",
    "hasEmergency": true,
    "transit": "Metro: Delhi Gate (Violet Line) · Gate 3 Entry"
  },
  {
    "id": "gtb-hospital-delhi",
    "name": "Guru Teg Bahadur (GTB) Hospital & UCMS",
    "shortName": "GTB Hospital Dilshad Garden",
    "address": "Taharpur Road, Dilshad Garden, Delhi 110095",
    "city": "New Delhi",
    "state": "Delhi",
    "locality": "North Delhi",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://delhi.gov.in/gtbh",
    "sourceLabel": "GTB Hospital Delhi",
    "hasEmergency": true,
    "transit": "Metro: Jhilmil / Mansarovar Park (Red Line)"
  },
  {
    "id": "nimhans-bengaluru",
    "name": "National Institute of Mental Health and Neurosciences (NIMHANS)",
    "shortName": "NIMHANS Bengaluru",
    "address": "Hosur Road, Lakkasandra, Bengaluru, Karnataka 560029",
    "city": "Bengaluru",
    "state": "Karnataka",
    "locality": "South Bengaluru",
    "departments": [
      "Neurology",
      "Psychiatry",
      "General Medicine",
      "Emergency"
    ],
    "sourceUrl": "https://nimhans.ac.in/",
    "sourceLabel": "NIMHANS clinical services",
    "hasEmergency": true,
    "transit": "Metro: South End Circle / Rashtreeya Vidyalaya Road · Hosur Road Main Gate"
  },
  {
    "id": "victoria-hospital-bengaluru",
    "name": "Victoria Hospital (Bangalore Medical College & Research Institute)",
    "shortName": "Victoria Hospital BMCRI",
    "address": "Fort Road, Near City Market, Kalasipalya, Bengaluru, Karnataka 560002",
    "city": "Bengaluru",
    "state": "Karnataka",
    "locality": "Central Bengaluru",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://bmcri.edu.in/",
    "sourceLabel": "BMCRI Victoria Hospital",
    "hasEmergency": true,
    "transit": "Metro: Krishna Rajendra Market (Green Line) · Fort Road Entry"
  },
  {
    "id": "bowring-hospital-bengaluru",
    "name": "Bowring and Lady Curzon Hospital",
    "shortName": "Bowring Hospital Shivajinagar",
    "address": "Lady Curzon Road, Tasker Town, Shivajinagar, Bengaluru, Karnataka 560001",
    "city": "Bengaluru",
    "state": "Karnataka",
    "locality": "Central Bengaluru",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://bowringandladycurzonhospital.karnataka.gov.in/",
    "sourceLabel": "Bowring Hospital public list",
    "hasEmergency": true,
    "transit": "Metro: MG Road / Cubbon Park (Purple Line) · 1 km from Shivajinagar Bus Station"
  },
  {
    "id": "kidwai-bengaluru",
    "name": "Kidwai Memorial Institute of Oncology",
    "shortName": "Kidwai Institute Bengaluru",
    "address": "Dr. M H Marigowda Road, Bengaluru, Karnataka 560029",
    "city": "Bengaluru",
    "state": "Karnataka",
    "locality": "South Bengaluru",
    "departments": [
      "General Medicine",
      "General Surgery",
      "Emergency",
      "Dermatology"
    ],
    "sourceUrl": "https://kmio.karnataka.gov.in/",
    "sourceLabel": "Kidwai Memorial Oncology",
    "hasEmergency": true,
    "transit": "Bus: Dairy Circle Stop · Near NIMHANS Campus"
  },
  {
    "id": "kem-hospital-mumbai",
    "name": "King Edward Memorial (KEM) Hospital & Seth GS Medical College",
    "shortName": "KEM Hospital Mumbai",
    "address": "Acharya Donde Marg, Parel, Mumbai, Maharashtra 400012",
    "city": "Mumbai",
    "state": "Maharashtra",
    "locality": "South Central Mumbai",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://www.kem.edu/",
    "sourceLabel": "KEM Hospital departments",
    "hasEmergency": true,
    "transit": "Local Train: Parel (Central) / Prabhadevi (Western) · Acharya Donde Marg Entry"
  },
  {
    "id": "sir-jj-hospital-mumbai",
    "name": "Sir JJ Group of Hospitals & Grant Medical College",
    "shortName": "Sir JJ Hospital Byculla",
    "address": "J J Marg, Nagpada, Byculla, Mumbai, Maharashtra 400008",
    "city": "Mumbai",
    "state": "Maharashtra",
    "locality": "South Mumbai",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://ggmcjjh.com/",
    "sourceLabel": "Grant Govt Medical College & JJ Hospital",
    "hasEmergency": true,
    "transit": "Local Train: Sandhurst Road / Byculla Station · JJ Flyover Junction"
  },
  {
    "id": "sion-hospital-mumbai",
    "name": "Lokmanya Tilak Municipal General Hospital (Sion Hospital)",
    "shortName": "Sion Hospital Mumbai",
    "address": "Sion West, Mumbai, Maharashtra 400022",
    "city": "Mumbai",
    "state": "Maharashtra",
    "locality": "Central Mumbai",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://ltmgh.com/",
    "sourceLabel": "LTMGH Sion Hospital",
    "hasEmergency": true,
    "transit": "Local Train: Sion (Central Line) / GTB Nagar (Harbour Line)"
  },
  {
    "id": "aiims-nagpur",
    "name": "All India Institute of Medical Sciences (AIIMS), Nagpur",
    "shortName": "AIIMS Nagpur",
    "address": "Plot No. 2, Sector 20, MIHAN, Nagpur, Maharashtra 441108",
    "city": "Nagpur",
    "state": "Maharashtra",
    "locality": "MIHAN Nagpur",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsnagpur.edu.in/",
    "sourceLabel": "AIIMS Nagpur clinical services",
    "hasEmergency": true,
    "transit": "Metro: Khapri Metro Station (Orange Line) · MIHAN Sector 20"
  },
  {
    "id": "bj-medical-pune",
    "name": "B.J. Government Medical College & Sassoon General Hospital",
    "shortName": "Sassoon Hospital Pune",
    "address": "Near Pune Railway Station, Sassoon Road, Pune, Maharashtra 411001",
    "city": "Pune",
    "state": "Maharashtra",
    "locality": "Central Pune",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://www.bjmcpune.org/",
    "sourceLabel": "BJMC Sassoon Hospital",
    "hasEmergency": true,
    "transit": "Railway: 300m from Pune Junction Railway Station · Metro: Pune Station Metro"
  },
  {
    "id": "pgimer-chandigarh",
    "name": "Postgraduate Institute of Medical Education & Research (PGIMER)",
    "shortName": "PGIMER Chandigarh",
    "address": "Sector 12, Chandigarh 160012",
    "city": "Chandigarh",
    "state": "Chandigarh",
    "locality": "Sector 12",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://pgimer.edu.in/",
    "sourceLabel": "PGIMER clinical departments",
    "hasEmergency": true,
    "transit": "Transit: CTU Bus Route 204/205 · Nehru Hospital Emergency Block Entry"
  },
  {
    "id": "gmch-32-chandigarh",
    "name": "Government Medical College and Hospital (GMCH-32)",
    "shortName": "GMCH Sector 32 Chandigarh",
    "address": "Chandi Path, Sector 32B, Chandigarh 160047",
    "city": "Chandigarh",
    "state": "Chandigarh",
    "locality": "Sector 32",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://gmch.gov.in/",
    "sourceLabel": "GMCH 32 public directory",
    "hasEmergency": true,
    "transit": "Transit: Sector 32 South Roundabout · Emergency Block Gate 1"
  },
  {
    "id": "aiims-bathinda",
    "name": "All India Institute of Medical Sciences (AIIMS), Bathinda",
    "shortName": "AIIMS Bathinda",
    "address": "Mandi Dabwali Road, Bathinda, Punjab 151001",
    "city": "Bathinda",
    "state": "Punjab",
    "locality": "Bathinda",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsbathinda.edu.in/",
    "sourceLabel": "AIIMS Bathinda OPD",
    "hasEmergency": true,
    "transit": "Highway: NH-54 Dabwali Road · Dedicated Institute Bus Terminal"
  },
  {
    "id": "kgmu-lucknow",
    "name": "King George's Medical University (KGMU), Lucknow",
    "shortName": "KGMU Lucknow",
    "address": "Shah Mina Road, Chowk, Lucknow, Uttar Pradesh 226003",
    "city": "Lucknow",
    "state": "Uttar Pradesh",
    "locality": "Chowk Lucknow",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://www.kgmu.org/",
    "sourceLabel": "KGMU hospital services",
    "hasEmergency": true,
    "transit": "Metro: KD Singh Babu Stadium · Shah Mina Road Trauma Centre Gate"
  },
  {
    "id": "sgpgi-lucknow",
    "name": "Sanjay Gandhi Postgraduate Institute of Medical Sciences (SGPGIMS)",
    "shortName": "SGPGIMS Lucknow",
    "address": "Raebareli Road, Lucknow, Uttar Pradesh 226014",
    "city": "Lucknow",
    "state": "Uttar Pradesh",
    "locality": "South Lucknow",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://www.sgpgims.org.in/",
    "sourceLabel": "SGPGIMS departments",
    "hasEmergency": true,
    "transit": "Road: Raebareli Highway (NH-24B) · SGPGIMS Main Entrance Gate"
  },
  {
    "id": "aiims-gorakhpur",
    "name": "All India Institute of Medical Sciences (AIIMS), Gorakhpur",
    "shortName": "AIIMS Gorakhpur",
    "address": "Kunraghat, Gorakhpur, Uttar Pradesh 273008",
    "city": "Gorakhpur",
    "state": "Uttar Pradesh",
    "locality": "Kunraghat",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsgorakhpur.edu.in/",
    "sourceLabel": "AIIMS Gorakhpur OPD",
    "hasEmergency": true,
    "transit": "Road: Deoria Road · 6 km from Gorakhpur Junction"
  },
  {
    "id": "ims-bhu-varanasi",
    "name": "Institute of Medical Sciences (IMS), Banaras Hindu University",
    "shortName": "Sir Sunderlal Hospital BHU",
    "address": "BHU Campus, Varanasi, Uttar Pradesh 221005",
    "city": "Varanasi",
    "state": "Uttar Pradesh",
    "locality": "BHU Varanasi",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://www.bhu.ac.in/ims/",
    "sourceLabel": "IMS BHU hospital portal",
    "hasEmergency": true,
    "transit": "Road: Lanka Gate BHU · Sir Sunderlal Hospital Emergency Wing"
  },
  {
    "id": "aiims-raebareli",
    "name": "All India Institute of Medical Sciences (AIIMS), Rae Bareli",
    "shortName": "AIIMS Rae Bareli",
    "address": "Munshiganj, Rae Bareli, Uttar Pradesh 229405",
    "city": "Rae Bareli",
    "state": "Uttar Pradesh",
    "locality": "Munshiganj",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsrbl.edu.in/",
    "sourceLabel": "AIIMS Rae Bareli services",
    "hasEmergency": true,
    "transit": "Road: Dalmau-Munshiganj Road · Institute Gate 1"
  },
  {
    "id": "aiims-rishikesh",
    "name": "All India Institute of Medical Sciences (AIIMS), Rishikesh",
    "shortName": "AIIMS Rishikesh",
    "address": "Virbhadra Road, Rishikesh, Uttarakhand 249203",
    "city": "Rishikesh",
    "state": "Uttarakhand",
    "locality": "Virbhadra",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsrishikesh.edu.in/",
    "sourceLabel": "AIIMS Rishikesh public directory",
    "hasEmergency": true,
    "transit": "Road: Haridwar-Rishikesh Highway · Virbhadra Rail Crossing Gate"
  },
  {
    "id": "doon-medical-dehradun",
    "name": "Government Doon Medical College & Hospital",
    "shortName": "Doon Hospital Dehradun",
    "address": "Parade Ground, Dehradun, Uttarakhand 248001",
    "city": "Dehradun",
    "state": "Uttarakhand",
    "locality": "Central Dehradun",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "http://gdmcuk.info/",
    "sourceLabel": "Doon Hospital public list",
    "hasEmergency": true,
    "transit": "Road: Clock Tower / Parade Ground · 2 km from Dehradun Railway Station"
  },
  {
    "id": "sskm-hospital-kolkata",
    "name": "IPGMER and SSKM Hospital, Kolkata",
    "shortName": "SSKM Hospital Kolkata",
    "address": "244 AJC Bose Road, Bhowanipore, Kolkata, West Bengal 700020",
    "city": "Kolkata",
    "state": "West Bengal",
    "locality": "South Kolkata",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://ipgmer.gov.in/",
    "sourceLabel": "IPGMER SSKM directory",
    "hasEmergency": true,
    "transit": "Metro: Rabindra Sadan (Blue Line) · AJC Bose Road Crossing Gate"
  },
  {
    "id": "calcutta-medical-college",
    "name": "Medical College and Hospital, Kolkata (Calcutta Medical College)",
    "shortName": "Calcutta Medical College",
    "address": "88 College Street, Bowbazar, Kolkata, West Bengal 700073",
    "city": "Kolkata",
    "state": "West Bengal",
    "locality": "Central Kolkata",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://www.medicalcollegekolkata.in/",
    "sourceLabel": "Calcutta Medical College",
    "hasEmergency": true,
    "transit": "Metro: Central / Mahatma Gandhi Road · College Street Gate"
  },
  {
    "id": "aiims-kalyani",
    "name": "All India Institute of Medical Sciences (AIIMS), Kalyani",
    "shortName": "AIIMS Kalyani",
    "address": "NH-34 Connector, Basantapur, Kalyani, West Bengal 741245",
    "city": "Kalyani",
    "state": "West Bengal",
    "locality": "Kalyani Nadia",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimskalyani.edu.in/",
    "sourceLabel": "AIIMS Kalyani OPD portal",
    "hasEmergency": true,
    "transit": "Rail: Kalyani Railway Station (Sealdah line) · NH-34 Connector"
  },
  {
    "id": "aiims-bhubaneswar",
    "name": "All India Institute of Medical Sciences (AIIMS), Bhubaneswar",
    "shortName": "AIIMS Bhubaneswar",
    "address": "Sijua, Patrapada, Bhubaneswar, Odisha 751019",
    "city": "Bhubaneswar",
    "state": "Odisha",
    "locality": "Patrapada",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsbhubaneswar.nic.in/",
    "sourceLabel": "AIIMS Bhubaneswar clinical care",
    "hasEmergency": true,
    "transit": "Road: Khandagiri-Chandaka Road · Sijua Campus Main Gate"
  },
  {
    "id": "scb-medical-cuttack",
    "name": "SCB Medical College and Hospital, Cuttack",
    "shortName": "SCB Hospital Cuttack",
    "address": "Mangalabag, Cuttack, Odisha 753007",
    "city": "Cuttack",
    "state": "Odisha",
    "locality": "Mangalabag",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://scbmch.in/",
    "sourceLabel": "SCB Medical College portal",
    "hasEmergency": true,
    "transit": "Rail: Cuttack Junction · Mangalabag Medical College Gate"
  },
  {
    "id": "aiims-patna",
    "name": "All India Institute of Medical Sciences (AIIMS), Patna",
    "shortName": "AIIMS Patna",
    "address": "Phulwari Sharif, Patna, Bihar 801507",
    "city": "Patna",
    "state": "Bihar",
    "locality": "Phulwari Sharif",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimspatna.edu.in/",
    "sourceLabel": "AIIMS Patna public directory",
    "hasEmergency": true,
    "transit": "Road: Khagaul Road · Phulwari Sharif AIIMS Flyover"
  },
  {
    "id": "pmch-patna",
    "name": "Patna Medical College and Hospital (PMCH)",
    "shortName": "PMCH Hospital Patna",
    "address": "Ashok Rajpath, Patna, Bihar 800004",
    "city": "Patna",
    "state": "Bihar",
    "locality": "Ashok Rajpath",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "http://pmch.ac.in/",
    "sourceLabel": "PMCH hospital directory",
    "hasEmergency": true,
    "transit": "Road: Ashok Rajpath along Ganges · Emergency Gate 1"
  },
  {
    "id": "nmch-patna",
    "name": "Nalanda Medical College and Hospital (NMCH)",
    "shortName": "NMCH Patna",
    "address": "Kankarbagh, Patna, Bihar 800026",
    "city": "Patna",
    "state": "Bihar",
    "locality": "Kankarbagh",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://nmchpatna.edu.in/",
    "sourceLabel": "NMCH hospital portal",
    "hasEmergency": true,
    "transit": "Road: Old Bypass Road · Kankarbagh Colony"
  },
  {
    "id": "mmc-rgggh-chennai",
    "name": "Rajiv Gandhi Government General Hospital & Madras Medical College",
    "shortName": "RGGGH Chennai",
    "address": "EVR Periyar Salai, Park Town, Chennai, Tamil Nadu 600003",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "locality": "Park Town Chennai",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://mmc.ac.in/",
    "sourceLabel": "Madras Medical College & RGGGH",
    "hasEmergency": true,
    "transit": "Metro/Suburban: Chennai Central / Chennai Park · Opposite Central Railway Station"
  },
  {
    "id": "stanley-medical-chennai",
    "name": "Government Stanley Medical College and Hospital",
    "shortName": "Stanley Hospital Chennai",
    "address": "Old Jail Road, Royapuram, Chennai, Tamil Nadu 600001",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "locality": "North Chennai",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://stanleymedicalcollege.ac.in/",
    "sourceLabel": "Stanley Medical College",
    "hasEmergency": true,
    "transit": "Metro: Washermanpet / Old Jail Road · Emergency Gate 2"
  },
  {
    "id": "aiims-madurai",
    "name": "All India Institute of Medical Sciences (AIIMS), Madurai",
    "shortName": "AIIMS Madurai",
    "address": "Thoppur, Madurai, Tamil Nadu 625008",
    "city": "Madurai",
    "state": "Tamil Nadu",
    "locality": "Thoppur",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsmadurai.edu.in/",
    "sourceLabel": "AIIMS Madurai portal",
    "hasEmergency": true,
    "transit": "Road: NH-7 Madurai-Tirunelveli Highway · Thoppur"
  },
  {
    "id": "jipmer-puducherry",
    "name": "Jawaharlal Institute of Postgraduate Medical Education & Research (JIPMER)",
    "shortName": "JIPMER Puducherry",
    "address": "Dhanvantari Nagar, Gorimedu, Puducherry 605006",
    "city": "Puducherry",
    "state": "Puducherry",
    "locality": "Gorimedu",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://jipmer.edu.in/",
    "sourceLabel": "JIPMER hospital directory",
    "hasEmergency": true,
    "transit": "Road: Tindivanam-Puducherry Highway · Dhanvantari Nagar Main Gate"
  },
  {
    "id": "aiims-mangalagiri",
    "name": "All India Institute of Medical Sciences (AIIMS), Mangalagiri",
    "shortName": "AIIMS Mangalagiri",
    "address": "Mangalagiri, Guntur District, Andhra Pradesh 522503",
    "city": "Vijayawada-Guntur",
    "state": "Andhra Pradesh",
    "locality": "Mangalagiri",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsmangalagiri.edu.in/",
    "sourceLabel": "AIIMS Mangalagiri clinical services",
    "hasEmergency": true,
    "transit": "Road: NH-16 between Vijayawada and Guntur · AIIMS Main Campus"
  },
  {
    "id": "kgh-visakhapatnam",
    "name": "King George Hospital & Andhra Medical College",
    "shortName": "King George Hospital Vizag",
    "address": "Collectorate Junction, Maharanipeta, Visakhapatnam, Andhra Pradesh 530002",
    "city": "Visakhapatnam",
    "state": "Andhra Pradesh",
    "locality": "Maharanipeta",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://kghvisakhapatnam.com/",
    "sourceLabel": "KGH Vizag public services",
    "hasEmergency": true,
    "transit": "Road: Collectorate Road · 4 km from Visakhapatnam Junction"
  },
  {
    "id": "nims-hyderabad",
    "name": "Nizam's Institute of Medical Sciences (NIMS)",
    "shortName": "NIMS Hyderabad",
    "address": "Punjagutta, Hyderabad, Telangana 500082",
    "city": "Hyderabad",
    "state": "Telangana",
    "locality": "Punjagutta",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://nims.edu.in/",
    "sourceLabel": "NIMS hospital departments",
    "hasEmergency": true,
    "transit": "Metro: Panjagutta Metro (Red Line) · Main Entrance Punjagutta Circle"
  },
  {
    "id": "osmania-hospital-hyderabad",
    "name": "Osmania General Hospital & Medical College",
    "shortName": "Osmania Hospital Hyderabad",
    "address": "Afzal Gunj, Hyderabad, Telangana 500012",
    "city": "Hyderabad",
    "state": "Telangana",
    "locality": "Afzal Gunj",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://osmaniahospital.telangana.gov.in/",
    "sourceLabel": "Osmania General Hospital",
    "hasEmergency": true,
    "transit": "Metro: MGBS / Malakpet · Afzal Gunj Bus Terminus"
  },
  {
    "id": "gandhi-hospital-secunderabad",
    "name": "Gandhi Hospital & Gandhi Medical College",
    "shortName": "Gandhi Hospital Secunderabad",
    "address": "Musheerabad, Padmarao Nagar, Secunderabad, Telangana 500003",
    "city": "Hyderabad",
    "state": "Telangana",
    "locality": "Secunderabad",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "http://gandhihospital.org/",
    "sourceLabel": "Gandhi Hospital public list",
    "hasEmergency": true,
    "transit": "Metro: Musheerabad / Gandhi Hospital Metro (Green Line)"
  },
  {
    "id": "aiims-jodhpur",
    "name": "All India Institute of Medical Sciences (AIIMS), Jodhpur",
    "shortName": "AIIMS Jodhpur",
    "address": "Basni Industrial Area Phase-2, Jodhpur, Rajasthan 342005",
    "city": "Jodhpur",
    "state": "Rajasthan",
    "locality": "Basni",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsjodhpur.edu.in/",
    "sourceLabel": "AIIMS Jodhpur hospital services",
    "hasEmergency": true,
    "transit": "Road: Basni Phase 2 · 8 km from Jodhpur Railway Station"
  },
  {
    "id": "sms-hospital-jaipur",
    "name": "Sawai Man Singh (SMS) Medical College & Hospital",
    "shortName": "SMS Hospital Jaipur",
    "address": "JLN Marg, Ashok Nagar, Jaipur, Rajasthan 302004",
    "city": "Jaipur",
    "state": "Rajasthan",
    "locality": "JLN Marg",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://medicaleducation.rajasthan.gov.in/smsjaipur",
    "sourceLabel": "SMS Medical College Jaipur",
    "hasEmergency": true,
    "transit": "Road: JLN Marg · 3 km from Jaipur Junction Railway Station"
  },
  {
    "id": "aiims-bhopal",
    "name": "All India Institute of Medical Sciences (AIIMS), Bhopal",
    "shortName": "AIIMS Bhopal",
    "address": "Saket Nagar, Bhopal, Madhya Pradesh 462020",
    "city": "Bhopal",
    "state": "Madhya Pradesh",
    "locality": "Saket Nagar",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsbhopal.edu.in/",
    "sourceLabel": "AIIMS Bhopal OPD portal",
    "hasEmergency": true,
    "transit": "Road: Saket Nagar AIIMS Road · 5 km from Habibganj (Rani Kamlapati) Station"
  },
  {
    "id": "my-hospital-indore",
    "name": "Maharaja Yeshwantrao (MY) Hospital & MGM Medical College",
    "shortName": "MY Hospital Indore",
    "address": "Sanyogitaganj, Indore, Madhya Pradesh 452001",
    "city": "Indore",
    "state": "Madhya Pradesh",
    "locality": "Sanyogitaganj",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://mgmmcindore.in/",
    "sourceLabel": "MGM Medical College & MY Hospital",
    "hasEmergency": true,
    "transit": "Road: Sanyogitaganj Main Road · Near Indore Junction"
  },
  {
    "id": "aiims-rajkot",
    "name": "All India Institute of Medical Sciences (AIIMS), Rajkot",
    "shortName": "AIIMS Rajkot",
    "address": "Khandheri, Para Pipaliya, Rajkot, Gujarat 360006",
    "city": "Rajkot",
    "state": "Gujarat",
    "locality": "Khandheri",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsrajkot.edu.in/",
    "sourceLabel": "AIIMS Rajkot OPD services",
    "hasEmergency": true,
    "transit": "Road: Jamnagar-Rajkot Highway · Khandheri Stadium Road"
  },
  {
    "id": "civil-hospital-ahmedabad",
    "name": "Civil Hospital Ahmedabad & B.J. Medical College",
    "shortName": "Civil Hospital Ahmedabad",
    "address": "Asarwa, Ahmedabad, Gujarat 380016",
    "city": "Ahmedabad",
    "state": "Gujarat",
    "locality": "Asarwa",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://bjmcabd.edu.in/",
    "sourceLabel": "BJMC Civil Hospital Ahmedabad",
    "hasEmergency": true,
    "transit": "Metro: Asarwa / Civil Hospital Metro (East-West Corridor)"
  },
  {
    "id": "aiims-guwahati",
    "name": "All India Institute of Medical Sciences (AIIMS), Guwahati",
    "shortName": "AIIMS Guwahati",
    "address": "Changsari, Kamrup, Guwahati, Assam 781101",
    "city": "Guwahati",
    "state": "Assam",
    "locality": "Changsari",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsguwahati.ac.in/",
    "sourceLabel": "AIIMS Guwahati portal",
    "hasEmergency": true,
    "transit": "Highway: NH-27 Changsari · 25 km from Guwahati Railway Station"
  },
  {
    "id": "gmch-guwahati",
    "name": "Gauhati Medical College and Hospital (GMCH)",
    "shortName": "GMCH Guwahati",
    "address": "Narakasur Hilltop, Bhangagarh, Guwahati, Assam 781032",
    "city": "Guwahati",
    "state": "Assam",
    "locality": "Bhangagarh",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://gmch.gov.in/",
    "sourceLabel": "GMCH hospital portal",
    "hasEmergency": true,
    "transit": "Road: GS Road / Bhangagarh Junction · 5 km from Guwahati Station"
  },
  {
    "id": "neigrihms-shillong",
    "name": "North Eastern Indira Gandhi Regional Institute of Health & Medical Sciences",
    "shortName": "NEIGRIHMS Shillong",
    "address": "Mawdiangdiang, Shillong, Meghalaya 793018",
    "city": "Shillong",
    "state": "Meghalaya",
    "locality": "Mawdiangdiang",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "http://neigrihms.gov.in/",
    "sourceLabel": "NEIGRIHMS Shillong directory",
    "hasEmergency": true,
    "transit": "Road: Mawdiangdiang Campus · 10 km from Police Bazar"
  },
  {
    "id": "aiims-jammu",
    "name": "All India Institute of Medical Sciences (AIIMS), Jammu",
    "shortName": "AIIMS Jammu",
    "address": "Vijaypur, Samba District, Jammu, Jammu & Kashmir 184120",
    "city": "Jammu",
    "state": "Jammu & Kashmir",
    "locality": "Vijaypur",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsjammu.edu.in/",
    "sourceLabel": "AIIMS Jammu OPD directory",
    "hasEmergency": true,
    "transit": "Highway: NH-44 Jammu-Pathankot Highway · Vijaypur"
  },
  {
    "id": "skims-srinagar",
    "name": "Sher-i-Kashmir Institute of Medical Sciences (SKIMS)",
    "shortName": "SKIMS Soura Srinagar",
    "address": "Soura, Srinagar, Jammu & Kashmir 190011",
    "city": "Srinagar",
    "state": "Jammu & Kashmir",
    "locality": "Soura",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://www.skims.ac.in/",
    "sourceLabel": "SKIMS clinical services",
    "hasEmergency": true,
    "transit": "Road: 90 Feet Road Soura · 8 km from Lal Chowk Srinagar"
  },
  {
    "id": "gmch-trivandrum",
    "name": "Government Medical College, Thiruvananthapuram",
    "shortName": "TMC Thiruvananthapuram",
    "address": "Medical College PO, Ulloor, Thiruvananthapuram, Kerala 695011",
    "city": "Thiruvananthapuram",
    "state": "Kerala",
    "locality": "Ulloor",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://tmc.kerala.gov.in/",
    "sourceLabel": "TMC hospital services",
    "hasEmergency": true,
    "transit": "Road: Medical College Junction · 5 km from Thiruvananthapuram Central"
  },
  {
    "id": "gmch-kozhikode",
    "name": "Government Medical College, Kozhikode (Calicut Medical College)",
    "shortName": "Calicut Medical College",
    "address": "Medical College Junction, Kozhikode, Kerala 673008",
    "city": "Kozhikode",
    "state": "Kerala",
    "locality": "Kozhikode",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "http://www.govtmedicalcollegekozhikode.ac.in/",
    "sourceLabel": "Calicut Medical College portal",
    "hasEmergency": true,
    "transit": "Road: Medical College Junction · 8 km from Kozhikode Railway Station"
  },
  {
    "id": "rims-ranchi",
    "name": "Rajendra Institute of Medical Sciences (RIMS), Ranchi",
    "shortName": "RIMS Ranchi",
    "address": "Bariatu, Ranchi, Jharkhand 834009",
    "city": "Ranchi",
    "state": "Jharkhand",
    "locality": "Bariatu",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://www.rimsranchi.ac.in/",
    "sourceLabel": "RIMS Ranchi public directory",
    "hasEmergency": true,
    "transit": "Road: Bariatu Road · 7 km from Ranchi Junction"
  },
  {
    "id": "aiims-deoghar",
    "name": "All India Institute of Medical Sciences (AIIMS), Deoghar",
    "shortName": "AIIMS Deoghar",
    "address": "Jasidih, Deoghar, Jharkhand 814142",
    "city": "Deoghar",
    "state": "Jharkhand",
    "locality": "Jasidih",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsdeoghar.edu.in/",
    "sourceLabel": "AIIMS Deoghar OPD portal",
    "hasEmergency": true,
    "transit": "Rail: 4 km from Jasidih Junction · Rohini Road"
  },
  {
    "id": "aiims-raipur",
    "name": "All India Institute of Medical Sciences (AIIMS), Raipur",
    "shortName": "AIIMS Raipur",
    "address": "GE Road, Tatibandh, Raipur, Chhattisgarh 492099",
    "city": "Raipur",
    "state": "Chhattisgarh",
    "locality": "Tatibandh",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsraipur.edu.in/",
    "sourceLabel": "AIIMS Raipur clinical departments",
    "hasEmergency": true,
    "transit": "Highway: NH-53 GE Road · Tatibandh Square Gate"
  },
  {
    "id": "aiims-bilaspur",
    "name": "All India Institute of Medical Sciences (AIIMS), Bilaspur",
    "shortName": "AIIMS Bilaspur",
    "address": "Kothipura, Bilaspur, Himachal Pradesh 174001",
    "city": "Bilaspur",
    "state": "Himachal Pradesh",
    "locality": "Kothipura",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://aiimsbilaspur.edu.in/",
    "sourceLabel": "AIIMS Bilaspur portal",
    "hasEmergency": true,
    "transit": "Highway: NH-205 Chandigarh-Manali Highway · Kothipura Campus"
  },
  {
    "id": "igmc-shimla",
    "name": "Indira Gandhi Medical College (IGMC), Shimla",
    "shortName": "IGMC Hospital Shimla",
    "address": "Snowdon, Shimla, Himachal Pradesh 171001",
    "city": "Shimla",
    "state": "Himachal Pradesh",
    "locality": "Snowdon",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "http://www.igmcshimla.edu.in/",
    "sourceLabel": "IGMC Shimla public directory",
    "hasEmergency": true,
    "transit": "Road: Circular Road / Snowdon · 3 km from Shimla Ridge"
  },
  {
    "id": "gmc-goa",
    "name": "Goa Medical College and Hospital (GMC), Bambolim",
    "shortName": "Goa Medical College",
    "address": "NH 66, Bambolim, Goa 403202",
    "city": "Panaji",
    "state": "Goa",
    "locality": "Bambolim",
    "departments": [
      "General Medicine",
      "Cardiology",
      "Orthopaedics",
      "Paediatrics",
      "Dermatology",
      "ENT",
      "Ophthalmology",
      "Gynaecology",
      "Neurology",
      "Gastroenterology",
      "Psychiatry",
      "Dental",
      "General Surgery",
      "Emergency"
    ],
    "sourceUrl": "https://gmc.goa.gov.in/",
    "sourceLabel": "GMC Goa hospital portal",
    "hasEmergency": true,
    "transit": "Highway: NH-66 Mumbai-Goa Highway · 5 km from Panaji"
  }
]);

export const INDIAN_STATES = Object.freeze([
  "All India",
  ...Array.from(new Set(PAN_INDIA_HOSPITALS.map((h) => h.state))).sort(),
]);

// A citizen chooses a locality. We never read device location. These figures are mock travel
// estimates from the chosen locality, not live routing or traffic data.
export const LOCALITIES = Object.freeze([
  { id: "central-delhi", label: "Central Delhi · New Delhi" },
  { id: "south-delhi", label: "South Delhi · New Delhi" },
  { id: "north-delhi", label: "North Delhi · New Delhi" },
  { id: "bengaluru-central", label: "Central Bengaluru · Karnataka" },
  { id: "mumbai-central", label: "South / Central Mumbai · Maharashtra" },
  { id: "chandigarh-tricity", label: "Chandigarh Tricity · Sector 12" },
  { id: "lucknow-central", label: "Central Lucknow · Chowk" },
  { id: "kolkata-central", label: "Central / South Kolkata · Bhowanipore" },
  { id: "hyderabad-central", label: "Hyderabad · Punjagutta" },
  { id: "chennai-central", label: "Central Chennai · Park Town" },
]);

const AVAILABILITY = Object.freeze({
  "aiims-new-delhi": {
    slot: "09:30",
    waitMinutes: 165,
    travel: {
      "central-delhi": { minutes: 35, distanceKm: 9.2 },
      "south-delhi": { minutes: 18, distanceKm: 4.8 },
      "north-delhi": { minutes: 48, distanceKm: 13.4 },
    },
  },
  "safdarjung-new-delhi": {
    slot: "10:00",
    waitMinutes: 150,
    travel: {
      "central-delhi": { minutes: 30, distanceKm: 7.4 },
      "south-delhi": { minutes: 14, distanceKm: 3.7 },
      "north-delhi": { minutes: 44, distanceKm: 12.1 },
    },
  },
  "rml-new-delhi": {
    slot: "10:30",
    waitMinutes: 130,
    travel: {
      "central-delhi": { minutes: 16, distanceKm: 4.1 },
      "south-delhi": { minutes: 32, distanceKm: 8.5 },
      "north-delhi": { minutes: 36, distanceKm: 9.8 },
    },
  },
});

const departmentAdjustments = Object.freeze({
  Cardiology: 0,
  "General Medicine": 10,
  Paediatrics: -5,
  Neurology: 15,
  Gastroenterology: 5,
  Orthopaedics: 0,
  Dermatology: 5,
  Dental: 0,
  Emergency: -20,
});

function minutesFromTime(time) {
  const [hours, minutes] = time.split(":").map(Number);
  return (hours * 60) + minutes;
}

function timeFromMinutes(totalMinutes) {
  const hours = Math.floor(totalMinutes / 60) % 24;
  const minutes = totalMinutes % 60;
  return `${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}`;
}

// Generates realistic, deterministic simulated wait & travel for pan-India hospitals
function getSimulatedAvailability(hospitalId, localityId) {
  if (AVAILABILITY[hospitalId]) {
    const base = AVAILABILITY[hospitalId];
    const travel = base.travel[localityId] || base.travel["central-delhi"] || { minutes: 25, distanceKm: 6.5 };
    return { slot: base.slot, waitMinutes: base.waitMinutes, travel };
  }
  // Deterministic pseudo-hash from hospital ID
  let hash = 0;
  for (let i = 0; i < hospitalId.length; i++) {
    hash = (hash * 31 + hospitalId.charCodeAt(i)) & 0xffff;
  }
  const slotMinutes = 540 + (hash % 120); // between 9:00 AM and 11:00 AM
  const slot = timeFromMinutes(slotMinutes);
  const waitMinutes = 120 + (hash % 70); // simulated wait between 120 and 190 mins
  const travelMinutes = 15 + (hash % 45);
  const distanceKm = Number((3.5 + (hash % 180) / 10).toFixed(1));
  return {
    slot,
    waitMinutes,
    travel: { minutes: travelMinutes, distanceKm },
  };
}

export function hospitalsForDepartment(department, localityId = "central-delhi", stateFilter = null) {
  const adjustment = departmentAdjustments[department] || 0;
  // If stateFilter is specifically supplied and not "All India", query PAN_INDIA_HOSPITALS
  // Otherwise, if default or localityId is one of Delhi's localities, preserve the 3 benchmark hospitals
  let candidateHospitals = HOSPITALS;

  if (stateFilter && stateFilter !== "Delhi" && stateFilter !== "All India") {
    candidateHospitals = PAN_INDIA_HOSPITALS.filter(h => h.state === stateFilter);
  } else if (stateFilter === "All India") {
    candidateHospitals = PAN_INDIA_HOSPITALS;
  }

  return candidateHospitals
    .filter((hospital) => hospital.departments.includes(department))
    .map((hospital) => {
      const base = getSimulatedAvailability(hospital.id, localityId);
      const waitMinutes = base.waitMinutes + adjustment;
      const slotMinutes = minutesFromTime(base.slot);
      const seenAt = timeFromMinutes(slotMinutes + waitMinutes);
      return {
        ...hospital,
        availability: {
          slot: base.slot,
          waitMinutes,
          seenAt,
          tokenRange: "1–12",
          travelMinutes: base.travel.minutes,
          distanceKm: base.travel.distanceKm,
          calendarOpens: "Slots for next week open Monday, 07:00.",
        },
      };
    })
    .sort((a, b) => (
      minutesFromTime(a.availability.seenAt) - minutesFromTime(b.availability.seenAt)
      || a.availability.travelMinutes - b.availability.travelMinutes
      || a.name.localeCompare(b.name)
    ));
}

export function panIndiaHospitalsForDepartment(department, state = null) {
  return hospitalsForDepartment(department, "central-delhi", state || "All India");
}

export function hospitalsByState(state = null) {
  if (!state || state === "All India") {
    return PAN_INDIA_HOSPITALS;
  }
  return PAN_INDIA_HOSPITALS.filter((h) => h.state === state);
}

export function formatWait(waitMinutes) {
  const hours = Math.floor(waitMinutes / 60);
  const minutes = waitMinutes % 60;
  return `${hours}h ${String(minutes).padStart(2, "0")}m`;
}
